deps: 
	mkdir deps
	cd deps; git clone https://github.com/OpenZeppelin/openzeppelin-contracts.git
	cd deps; git clone https://github.com/Uniswap/v3-core.git
	cd deps; git clone https://github.com/Uniswap/v3-periphery.git
	cd deps; git clone https://github.com/Uniswap/swap-router-contracts.git
