deps: 
	mkdir deps
	cd deps; git clone https://github.com/OpenZeppelin/openzeppelin-contracts.git
	cd deps; git clone https://github.com/Uniswap/v3-core
	cd deps; git clone https://github.com/Uniswap/v3-periphery
